title: Guilherme Vieira # your name (or website title) here
logo: "/images/profile_linkedin.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computational Scientist | Fluid Mechanics 
  <br><br>
  Computational researcher in fluid mechanics, with experience in numerical simulations of ocean processes. Expertise in numerical modeling, code validation, data processing, analysis, and pattern identification.   Multilingual, global citizen, interested in using mathematical modeling to better understand the world we inhabit and how we experience it.
  <br><br>
  <a href="https://www.linkedin.com/in/guilherme-s-vieira/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
